### ISSUE TITLE
gene not recognized

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1114]
I'm trying to add lsm6 SPAC2F3.17c to session c9f33602640ff7ad using the genotype management interface
but I get an error message saying the gene is not recognized

Its systematic ID is a synonym of another gene so maybe that's the problem? (I can't add it based on primary name or sys ID)

I then tried to add it via the *add another gene* route (which would be a more normal way to add a gene I guess) and after bunging the gene name in I now get this error in the session:
(en) Please come back later
(fr) SVP veuillez revenir plus tard
(de) Bitte versuchen sie es spaeter nocheinmal
(at) Konnten's bitt'schoen spaeter nochmal reinschauen
(no) Vennligst prov igjen senere
(dk) Venligst prov igen senere
(pl) Prosze sprobowac pozniej
(pt) Por favor volte mais tarde
(ru) Попробуйте еще раз позже
(ua) Спробуйте ще раз пізніше
(it) Per favore riprova più tardi

**Comment by kimrutherford** [comment]
> Please come back later

Oh dear.  Is that the test Canto or the main one?

**Comment by Antonialock** [comment]
main one. I think it has to do with adding the lsm6 gene

**Comment by kimrutherford** [comment]
> main one. I think it has to do with adding the lsm6 gene

OK, thanks.  I'll look at that today.

**Comment by kimrutherford** [comment]
> Its systematic ID is a synonym of another gene so maybe that's the problem?

Yep, I've had a look and that's what's causing it.  I'll make it smarter about that.

**Comment by kimrutherford** [comment]
This is fixed in the test Canto.  And should be in the main Canto soon.

**Comment by Antonialock** [comment]
I tried a hard refresh + a different browser and when I go to 
https://curation.pombase.org/pombe/curs/c9f33602640ff7ad/
I still get:

(en) Please come back later
(fr) SVP veuillez revenir plus tard
(de) Bitte versuchen sie es spaeter nocheinmal
(at) Konnten's bitt'schoen spaeter nochmal reinschauen
(no) Vennligst prov igjen senere
(dk) Venligst prov igen senere
(pl) Prosze sprobowac pozniej
(pt) Por favor volte mais tarde
(ru) Попробуйте еще раз позже
(ua) Спробуйте ще раз пізніше
(it) Per favore riprova più tardi

**Comment by kimrutherford** [comment]
>  And should be in the main Canto soon.

I was hoping to finish the upgrade to the new code today which would have fixed it for you.  If you need to finish the session before we do the extension upgrade I can fix the main Canto.  It's a little bit fiddly to do fix this problem without bringing in all the extension changes, but I can do it if you need it.

**Comment by Antonialock** [comment]
no it's ok!

**Comment by kimrutherford** [comment]
This looks OK now - no errors when going to session c9f33602640ff7ad.
