### ISSUE TITLE
cant create  genotypes in genotype management

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1832]
I can create deletions in the  single gene interface and combine them though...

**Comment by kimrutherford** [comment]
Sorry for breaking things.  I wasn't careful enough when I made some of the recent changes for Fly-Canto.

I think I've fixed it.  Let me know if things work for you now.

@jseager7 could you test the genotype management "Deletion" and "Other genotype ..." buttons in PHI mode when you get back to work?  Cheers.

**Comment by ValWood** [comment]
now fine for me.

**Comment by jseager7** [comment]
This bug still happens in pathogen-host mode on the latest revision of `master` (0ff28eba04abd7605c79aab09de95f1e3ecc77d8). I get this error message in Chrome's console whenever I try to make a quick deletion:

```
TypeError: Cannot read property 'taxonid' of undefined
    at m.$scope.deleteSelectStrainPicker (canto-modules.js:4219)
    [...]
```

And I get this error when I try to make any other genotype:

```
angular.js:14199 TypeError: Cannot read property 'taxonid' of undefined
    at m.$scope.singleAlleleQuick (canto-modules.js:4191)
    [...]
```
It looks like the genes that are being passed in to `GenotypeGeneListCtrl` don't have an organism object attached to them.

I've debugged the code and it looks like the organism properties are there when they're fetched by `CursGeneList.geneList()` in `genotypeManageCtrl`, but the organisms are somehow lost when the following lines of code are run in `$scope.updateVisibleGenes`:

```javascript
$scope.data.visibleGenes.length = 0;
[].push.apply($scope.data.visibleGenes, $scope.data.selectedOrganism.genes);
```

The properties that remain after this transformation are:

- `display_name`
- `gene_id`
- `primary_identifier`
- `primary_name`

But the following properties are missing: 

- `organism`
- `feature_id`

**Comment by kimrutherford** [comment]
Thanks for finding the broken code.  I've fixed things in the master branch by adding the organism to the genes from `$scope.data.selectedOrganism.genes`.  The genes data in the selected organism doesn't include the organism field (which makes sense), so I've added it.

**Comment by jseager7** [comment]
I've tested this now, and creating genotypes works as expected. Thanks.
