### ISSUE TITLE
Support rescue experiments

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1986]

**Comment by kimrutherford** [comment]
While talking to Gillian and Vitor last week I made a note to create this issue but I don't know the details so I left the description blank.  I should have made better notes.

@gm119 @vmt25 was this something that you'll need for FlyBase?  If so, could you at add a comment?  Cheers!

**Comment by vmt25** [comment]
#1986 and #1985 are related, as they are 'genetic interactions' within the same gene.

This case is for 'genetic interactions' between genotypes of the same gene in which e.g. a transgene for gene X is used to rescue a mutant for gene X (e.g. X[-]/X[-]).

General scheme is 
genotype A of gene X - interaction type - genotype B of same gene X
eg: cdc2 transgene rescues cdc2[delta]/cdc2[delta].

Specifications are:
1 - Both genotypes must concerns same gene X in the form of:

    a) 'pure' single gene genotypes
        i) same locus genotypes as either single allele or diploid (heterozygotes, homozygotes, transheterozygotes, transheterozygotes with deficiencies/aberrations)
        ii) multiple locus genotypes alleles of the same gene - e.g. wg[transgene A]+wg[transgene B], which are inserted at different loci

    b) multi-gene genotypes in which all other alleles are of the 'accessory' type.

This may not be the clearest of explanations, so feel free to ask for clarifications

**Comment by kimrutherford** [comment]
Have I got this right?:

 - the genotype A list should only contain genotypes where all alleles come from the same gene (ignoring accessory alleles) - so: single gene genotypes
 - the genotype B list should have the same restriction but also should list only genotypes from the same gene as selected from the genotype A list

**Comment by vmt25** [comment]
> Have I got this right?:
> 
>     * the genotype A list should only contain genotypes where all alleles come from the same gene (ignoring accessory alleles) - so: single gene genotypes
> 
>     * the genotype B list should have the same restriction but also should list only genotypes from the same gene as selected from the genotype A list

Correct!

**Comment by kimrutherford** [comment]
I've had a go at implementing this.  Please let me if you see any problems.  What should the interaction types be?

Here's my example session: https://curation.pombase.org/flybase-test/curs/2e523d5ee64ea295

**Comment by vmt25** [comment]
> I've had a go at implementing this. Please let me if you see any problems. 

There are a few issues here:

1. Selecting the single allele Pdf[01] leads to the message '(there are no other genotypes for gene in this session)'. However, there is another single allele for the Pdf gene, Pdf[UAS.cSa], and, therefore, an annotation should be possible.
The same happens when I select Pdf[UAS.cSa] as the initial genotype.

![Screenshot 2019-08-19 at 12 02 20](https://user-images.githubusercontent.com/33721108/63261242-e24ce680-c27a-11e9-913b-18139f2e6ea9.png)



I created 'Pdf[UAS.cSa], Scer\GAL4[elav.PLu](accessory)', which should be considered a single gene genotype because Scer\GAL4[elav.PLu] is an accessory allele. However, it does not appear on the list of genes. I also created 'Pdf[01]/Pdf[01]' (diploid homozygous condition), which appears fine on the list.


![Screenshot 2019-08-19 at 12 16 13](https://user-images.githubusercontent.com/33721108/63261355-33f57100-c27b-11e9-94f8-3cb827b91ed5.png)



> What should the interaction types be?

There are three rescue evidence types:
Rescues
Partially rescues
Fails to rescue

**Comment by kimrutherford** [comment]
Sorry about that!  I broke things before you had a chance to try.  I've fixed it now.

> There are three rescue evidence types:

Thanks.  I've added "Fails to rescue"

**Comment by vmt25** [comment]
All three rescue types are showing up - thanks
The new Pdf[01] homozygous genotype is also showing up on the drop down - thanks
The new 'Pdf[UAS.cSa], Scer\GAL4[elav.PLu]' genotype is still not showing up on the drop down.

**Comment by vmt25** [comment]
Cannot finalize a rescue annotation because Canto says the 'interaction type' filed needs input despite it already having a value:

![Untitled](https://user-images.githubusercontent.com/33721108/63339097-13412000-c33c-11e9-83ed-4fcc3d6c8ca5.png)

**Comment by kimrutherford** [comment]
> Cannot finalize a rescue annotation because Canto says the 'interaction type' filed needs input
> despite it already having a value:

Sorry about that.  It's fixed now.

**Comment by kimrutherford** [comment]
> The new 'Pdf[UAS.cSa], Scer\GAL4[elav.PLu]' genotype is still not showing up on the drop down.

I think I've fixed that.

**Comment by vmt25** [comment]
Working! Coolio.

**Comment by vmt25** [comment]
Diploids include a deletion/aberration - e.g. Notch[1]/Df(2R)XXXXX - should show up on the drop-down of interacting, as these are considered single gene genotypes - in this case a genotype of the gene Notch.

**Comment by kimrutherford** [comment]
> Diploids include a deletion/aberration - e.g. Notch[1]/Df(2R)XXXXX - should show up on
> the drop-down of interacting, as these are considered single gene genotypes - in this
> case a genotype of the gene Notch.

Thanks Vitor.

I think I forgot to implement this bit from your descriotion of what was needed:

> b) or multi-gene genotypes in which all other alleles are of the 'accessory' type.

I'll work on it!

**Comment by vmt25** [comment]
yes, please.
Thanks

**Comment by kimrutherford** [comment]
> I think I forgot to implement this bit from your description of what was needed:
>>    b) or multi-gene genotypes in which all other alleles are of the 'accessory' type.
>
> I'll work on it!

It looks like I had implemented but I forgot.  So I think this is done.

I'm going to close the issue but please re-open or create new issues if there are any problems.
