### ISSUE TITLE
Strain picker doesn't handle strain names with slashes correctly

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2024]
@CuzickA noticed that the strain picker behaves incorrectly when a strain name is selected that has a forward slash in it, for example BALB/C:

![strain selector error](https://user-images.githubusercontent.com/37659591/65234351-4f4ada80-dacc-11e9-9f2b-a37f72b5f051.png)

It seems like Canto behaves as if the character or text after the slash isn't there, meaning it views BALB/c and BALB/C as equivalent ~(although this could also be due to case-insensitive comparisons)~. For some organisms, like _Mus musculus_, this bug prevents users from adding most strains in the list.

**Comment by jseager7** [comment]
I've investigated this and I think the probable cause of the bug is that the forward slashes aren't encoded before they're passed to the `Curs` service. The bug occurs in the `add` method:

```js
  this.add = function (key, args) {
    if (!args) {
      args = [];
    }

    var url = curs_root_uri + '/ws/' + key + '/add/' + args.join('/');
    return $http.get(url)
      .then(function(response) {
        return response.data;
      });
  };
```

If there's already a slash in the strain name, then the URL ends up like this:

```
ws/strain_by_name/add/10090/BALB/c
```
Which presumably means the 'c' after the final slash is ignored, so the webservice parses the strain to be added as just 'BALB'. If the slash was encoded, we wouldn't have this problem:
```
ws/strain_by_name/add/10090/BALB%2Fc
```
I'll open a pull request to fix this.

**Comment by jseager7** [comment]
I've tried solving this by applying URI encoding on the front-end:

```js
args = args.map(encodeURIComponent)
```

...but it doesn't seem to stop the bug from happening: the strains are still returned with everything after and including the slash removed.

Next, I tried to replace the slash with a different character entirely:

```js
args = args.map(function (x) { return x.replace('/', '-') });
```

And for some reason, this works &ndash; the strain is stored and retrieved with no problems:

![image](https://user-images.githubusercontent.com/37659591/65243895-41538480-dae1-11e9-9f9c-3a7d25d808eb.png)

I can't seem to track down exactly when the text following the slash gets lost; my suspicion is that it's on the back-end, since the strain names are already broken by the time they're returned from `Curs.list`, even if the slashes were URI encoded when the strain was stored with `Curs.add`.

@kimrutherford Do you think you could debug what happens on the back-end? Most _Mus musculus_ strains are good candidates for triggering the bug, since a lot of them have slashes in the strain names.

**Comment by kimrutherford** [comment]
> the strains are still returned with everything after and including the slash removed.

It's possible that the back end is messing things up.  I'll investigate.

**Comment by kimrutherford** [comment]
Hi James.  I've pushed a fix for that.  Could you check that it fixes the issue you're seeing?

**Comment by jseager7** [comment]
@kimrutherford The fix works for creating strains, but it's still having problems when attempting to delete a strain. Canto gives the following error message in a popup:

> Failed to remove strain
> can't find strain with name BALB for taxon ID 10090

![image](https://user-images.githubusercontent.com/37659591/66314044-56b31600-e90b-11e9-8b03-cb5fd99a12b1.png)

It's possible that this bug is on the front-end, though.

**Comment by jseager7** [comment]
Actually, I've just noticed the problem: `ws_delete_strain_by_name` doesn't have the same fix applied. That's simple enough that I can try a fix by myself.

**Comment by kimrutherford** [comment]
> Actually, I've just noticed the problem: ws_delete_strain_by_name doesn't have the same fix
> applied. That's simple enough that I can try a fix by myself.

Thanks.
