### ISSUE TITLE
no options to curate GI

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2699]
I could not add a GI for this double mutant, there were no menu options available:

<img width="1179" alt="Screenshot 2023-02-28 at 15 05 11" src="https://user-images.githubusercontent.com/7359272/221897998-7333439d-7f4b-4eae-ac7c-8db3fcce5c6a.png">

**Comment by ValWood** [comment]
curs/88f3e63970618c74

**Comment by ValWood** [comment]
expected 
Phenotypic Enhancement

**Comment by kimrutherford** [comment]
It's doing what the configuration says:
  - it's not a population phenotype so the type must be one of:
     - Phenotypic Enhancement
     - Phenotypic Suppression
  - and it's not a double deletion and neither allele is overexpressed so it also must be one of:
    - Synthetic Growth Defect
    - Synthetic Lethality
    - Synthetic Rescue

and the intersection of those lists is empty.

**Comment by ValWood** [comment]
OK, I'll look at this today. I might be making the annotation incorretly.

**Comment by manulera** [comment]
Hi @kimrutherford @ValWood 

I think this interaction should be allowed from what we discussed:

https://www.pombase.org/documentation/genetic-and-physical-interactions

Phenotypic enhancement / suppression should be allowed for any type of alleles (no restriction on allele types). `not_population_evidence_codes` should be the only restriction.

**Comment by ValWood** [comment]
Agreed, sorry for the slowness, working backwards!

**Comment by kimrutherford** [comment]
I think I've fixed this.  Could you check that it's OK?

**Comment by ValWood** [comment]
Yes it works.

2 thoughts:
1. If we select a phenotype that is enhanced or repressed, it seems to be possible to edit the rescued phenotype with no consequences 
2. For phneotypic enhancement it might be a bit strange sometimes to select a "enhanced phenotype"  and/or a direction.
For example if 2 'normal' exhibit a defect when combined. We may need to relax the need to select a direction and a phenotype.

**Comment by manulera** [comment]
> For example if 2 'normal' exhibit a defect when combined. We may need to relax the need to select a direction and a phenotype.

We asked this to BioGrid and they said this in their email:

> Your example of a synthetic phenotype (non-growth or viability) that does not exist in the single mutants is a good example. When we came across examples like this in the literature we decided to use "phenotypic enhancement" as a best fit option. Although it's not ideal as it implies the presence of the phenotype in one of the starting single mutants.

Full response here: https://github.com/pombase/curation/issues/3295

**Comment by ValWood** [comment]
The problem is that in Canto currently you have to choose  an x enhances y option. We would not always want to do this (in the example I was curating it was OK)

**Comment by kimrutherford** [comment]
> The problem is that in Canto currently you have to choose an x enhances y option. We would not always want to do this

Could you explain this to me on the next call?  Sorry, I don't follow.

**Comment by manulera** [comment]
Hey @kimrutherford we can talk about this today, but essentially a "synthetic phenotype" is a phenotype that occurs in a double mutant without occurring in either of the single mutants. It's similar to "synthetic lethality" (single mutants are viable, but double mutant is lethal).

This is not captured by BioGrid's genetic interactions, and their email advice was to capture it as a "phenotypic enhancement", even if it's not strictly that. This cannot be done in Canto as is, because a "phenotypic enhancement" forces you to pick a phenotype for the single mutant that is enhanced in the double (rightly so, according to its definition).

To be honest, not sure if it makes sense to do it like that. It can be misleading, and in the end the phenotype is captured as a double mutant anyway. The only problem is that if someone uses our GIs to establish links between genes, these links would be missing. Alternatively, we could define a new type of GI for synthetic phenotype that does not require a link to a single mutant phenotype. I don't think it's that crazy considering this is very common, and it's similar to the synthetic lethality concept.

**Comment by manulera** [comment]
@kimrutherford adding some info as discussed this morning, regarding the new genetic interaction "Synthetic phenotype":

* Definition: A genetic interaction is inferred when mutations or deletions in separate genes produce a phenotype that is not present in either of the single mutations or deletions under a given condition.
* The interaction is symmetrical
* Constrains: same constrains that apply to "Phenotypic enhancement" or "Phenotypic suppression", but there is no need to pick a single mutant phenotype.
* BioGrid: when exporting to BioGrid, they should be converted into "Phenotypic enhancement".

I tried to put this in the canto.yaml file, hopefully I did it right. The only thing I did not know is where to indicate that this type of GI does not need to link to a single allele phenotype.

**Comment by manulera** [comment]
The PR: https://github.com/pombase/canto/pull/2707

**Comment by kimrutherford** [comment]
> I tried to put this in the canto.yaml file, hopefully I did it right. 

Look good to me.  Thanks!

I've merged and deployed the config change.  Could you let me know if it's working OK?

**Comment by manulera** [comment]
In the Canto test server this does not seem to work. 

![Screenshot 2023-03-15 at 09 21 58](https://user-images.githubusercontent.com/22526102/225264936-c31e7573-a85d-4f8a-a735-2570ba301c56.png)

This is for a double deletion with phenotype "short spindle".

Also there is still one problem with constrains for knockdown alleles. I cannot pick cut7D pkl1+[knockdown] for a phenotypic enhancement or suppression. I thought this would be enabled through this.

```yaml
one_allele_overexpressed:
        - Dosage Growth Defect
        - Dosage Lethality
        - Dosage Rescue
        - Phenotypic Enhancement
        - Phenotypic Suppression
        - Synthetic Phenotype
```

In any case, Phenotypic Suppression, Enhancement and Synthetic Phenotype should not be constrain at all by expression level, only by the phenotype not being a cell population growth or cell population viability phenotype.

**Comment by manulera** [comment]
Btw there were also these errors, forgot to attach the screenshot:

![Screenshot 2023-03-15 at 10 19 28](https://user-images.githubusercontent.com/22526102/225280011-5a4ddcf1-f930-43e5-9aae-64742f8885fc.png)

**Comment by manulera** [comment]
Hi @kimrutherford there are still some problems with the constrains:

* Cell population growth phenotypes should not offer "Synthetic phenotype" as an option ("Synthetic growth defect" covers this). I can select "Synthetic phenotype" in a double mutant with "decreased vegetative cell population growth".
* Knockdowns are still not selectable for "Phenotypic enhancement" or "Phenotypic Suppression":
    ![Screenshot 2023-03-15 at 11 57 04](https://user-images.githubusercontent.com/22526102/225302267-665907e0-e250-489f-842a-801afc5970fc.png)
    This only allows "Synthetic Phenotype"

**Comment by manulera** [comment]
I have updated the decision tree to cover this, I will update the website file next:

```mermaid
flowchart TD;
    A[Is the double<br>mutant lethal?<br>];
    A -->|Yes| C{{The single allele <br> must be viable}};
    C --> C2[Is the interacting<br>allele overexpressed?];
    C2 -->|Yes| C2.1((Dosage<br>Lethality));
    C2 -->|No| C2.2((Synthetic<br>Lethality));
    A -->|No| D[Is the single<br>mutant lethal?];
    D -->|Yes| E{{The double mutant <br> must be viable.}};
    E --> E2[Is the interacting<br>allele overexpressed?];
    E2 -->|Yes| E2.1((Dosage<br>Rescue));
    E2 -->|No| E2.2((Synthetic<br>Rescue));
    D -->|No| G[Is one of the<br>phenotypes a cell<br> population growth<br>phenotype?];
    G -->|Yes| H{{The other phenotype<br> should be a population <br> growth phenotype too}};
    H -->H2[Is the interacting<br>allele overexpressed?];
    H2 -->|Yes| H2.1[Double mutant is <br>worse than single?];
        H2.1 -->|Yes| H2.1.1((Dosage<br>Growth<br>Defect));
        H2.1 -->|No| H2.1.2((Dosage<br>Rescue));
    H2 -->|No| H2.2[Double mutant is <br>worse than single?];
        H2.2 -->|Yes| H2.2.1((Synthetic<br>Growth<br>Defect));
        H2.2 -->|No| H2.2.2((Synthetic<br>Rescue));
    G -->|No| GG[Do any of the<br> single alleles<br>have the phenotype?]
    GG -->|Yes| I[Double mutant is <br>worse than single?];
    I -->|Yes| J((Phenotypic<br>Enhancement));
    I -->|No| K((Phenotypic<br>Suppresion));
    GG -->|No| L((Synthetic<br>Phenotype))
```

**Comment by manulera** [comment]
I have created a PR updating the documentation in the website. In addition, I have added the mermaid code to generate the image in a hidden div in the markdown file, in case it needs adjustment in the future:

https://github.com/pombase/website/blob/32af4b9e4974afad2e8dfaa2ca8f14cabb86d00b/src/docs/documentation/genetic-and-physical-interactions.md?plain=1#L57-L90

**Comment by kimrutherford** [comment]
> This only allows "Synthetic Phenotype"

It might be a caching issue.  The test server sometime has problems with that.  Could you try shift-reload?

**Comment by manulera** [comment]
Hi @kimrutherford. Tested with you this morning during the call. Most was fixed except for this:

Cell population growth phenotypes should not offer "Synthetic phenotype" as an option ("Synthetic growth defect" covers this). I can select "Synthetic phenotype" in a double mutant with "decreased vegetative cell population growth".

Also after our call, I added this 'name' properties to the GIs in `canto.yaml`:
https://github.com/pombase/canto/commit/8eb0d830f27bb8da8cb0692c81d92f041a3e13ef

**Comment by kimrutherford** [comment]
Hi @manulera

I think I've fixed this.  Can you check when you have time?

**Comment by manulera** [comment]
Hi @kimrutherford. I still see the same, not sure if the code is available in the test instance, because my text does not appear in the parenthesis of synthetic phenotype either (I did hard reload)

**Comment by kimrutherford** [comment]
Hi Manu.  I only updated the main Canto.  I should have said.

**Comment by manulera** [comment]
Tried it there, looks good!

**Comment by kimrutherford** [comment]
OK, thanks!
